### ISSUE TITLE
kfp 2.3.0 upgrade `frontend` rock

### ISSUE THREAD

**Issue by NohaIhab** [canonical/pipelines-rocks#153]
### Context

Related to https://github.com/canonical/kfp-operators/issues/581
Upgrade the the rock for 2.3.0 kfp

### What needs to get done

Upgrade the rock

### Definition of Done

1. Rock is upgraded for kfp 2.3.0
2. Rock is on Dockerhub

**Comment by orfeas-k** [comment]
Note that during the upgrade, we hit the following issue:

In the CI it failed with the following error
```
2024-11-28 09:44:15.487 :: + npx yarn licenses generate-disclaimer
2024-11-28 09:44:18.890 :: /root/.npm/_npx/c094c3349f8dd527/node_modules/yarn/lib/cli.js:89452
2024-11-28 09:44:18.891 ::   throw err;
2024-11-28 09:44:18.891 ::   ^
2024-11-28 09:44:18.891 ::
2024-11-28 09:44:18.891 :: Error: EACCES: permission denied, write
2024-11-28 09:44:18.891 ::     at writeSync (node:fs:929:3)
2024-11-28 09:44:18.892 ::     at SyncWriteStream._write (node:internal/fs/sync_write_stream:27:5)
2024-11-28 09:44:18.892 ::     at writeOrBuffer (node:internal/streams/writable:392:12)
2024-11-28 09:44:18.892 ::     at _write (node:internal/streams/writable:333:10)
2024-11-28 09:44:18.892 ::     at Writable.write (node:internal/streams/writable:337:10)
2024-11-28 09:44:18.893 ::     at console.value (node:internal/console/constructor:305:16)
2024-11-28 09:44:18.893 ::     at console.log (node:internal/console/constructor:380:26)
2024-11-28 09:44:18.893 ::     at /root/.npm/_npx/c094c3349f8dd527/node_modules/yarn/lib/cli.js:86037:15
2024-11-28 09:44:18.893 ::     at Generator.next (<anonymous>)
2024-11-28 09:44:18.893 ::     at step (/root/.npm/_npx/c094c3349f8dd527/node_modules/yarn/lib/cli.js:310:30) {
2024-11-28 09:44:18.893 ::   errno: -13,
2024-11-28 09:44:18.894 ::   syscall: 'write',
2024-11-28 09:44:18.894 ::   code: 'EACCES'
2024-11-28 09:44:18.894 :: }
2024-11-28 09:44:18.894 ::
2024-11-28 09:44:18.894 :: Node.js v18.20.4
2024-11-28 09:44:19.108 'override-build' in part 'backend' failed with code 1.
```
at command ` npx yarn licenses generate-disclaimer` of the script, while locally it goes past this step but fails during `npm ci` step (after the script) with:

```
:: 37 vulnerabilities (6 low, 6 moderate, 20 high, 5 critical)                                   ::                                                                                               :: To address issues that do not require attention, run:                                         ::   npm audit fix                                                                               ::                                                                                               :: To address all issues possible (including breaking changes), run:                             ::   npm audit fix --force                                                                       ::                                                                                               :: Some issues need review, and may require choosing                                             :: a different dependency.                                                                       ::                                                                                               :: Run `npm audit` for details.                                                                  :: + npm run build                                                                               ::                                                                                               :: > build                                                                                       :: > tsc --project .                                                                             ::                                                                                               :: sh: 1: tsc: not found                                                                         'override-build' in part 'backend' failed with code 127.                                        
```

@NohaIhab  figured out that this could be due to the node version as mentioned in this PR https://github.com/kubeflow/pipelines/pull/10794.
In order to pin the node then to 18.18.2 (to follow what upstream dockerfile does), we tried to use [npm-node-version](https://documentation.ubuntu.com/rockcraft/en/stable/common/craft-parts/reference/plugins/npm_plugin/#npm-node-version) and `npm-include-node` fields of plugin `npm`. However, this resulted in the following errors:
```
:: + npm install -D yarn 
:: ./scripts/yarn-licenses.sh: line 6: npm: command not found
```
it turns out that `npm` plugin is in a bad state right now and using those has no effect when using with `override-build`.

Thus, we fell back to `nil` plugin and manual installation of npm and node, similar to what we already did in `install-node` part.
