### ISSUE TITLE
visualisation-server ROCK fails to build

### ISSUE THREAD

**Issue by i-chvets** [canonical/pipelines-rocks#29]
# Description
visualisation-server fails to be build in GH runner.
Need to investigate what is causing the issue.

Logs from GH ruuner (https://github.com/canonical/pipelines-rocks/actions/runs/5639877801/job/15275708711)
```
Run canonical/craft-actions/rockcraft-pack@main
Building ROCK in "visualisation-server"...
Installing Rockcraft plus dependencies
/usr/bin/sg lxd -c rockcraft pack --verbosity trace
2023-07-24 02:04:[5](https://github.com/canonical/pipelines-rocks/actions/runs/5639877801/job/15275708711#step:5:6)3.882 Starting Rockcraft 0.0.1.dev1
2023-07-24 02:04:53.882 Logging execution to '/home/runner/.local/state/rockcraft/log/rockcraft-20230724-020453.881375.log'
2023-07-24 02:04:53.882 Raw pre-parsed sysargs: args={'help': False, 'verbose': False, 'quiet': False, 'verbosity': 'trace', 'version': False} filtered=['pack']
2023-07-24 02:04:53.882 General parsed sysargs: command='pack' args=[]
2023-07-24 02:04:53.884 Command parsed sysargs: Namespace(debug=False, destructive_mode=False)
2023-07-24 02:04:53.884 lifecycle command: 'pack', arguments: Namespace(debug=False, destructive_mode=False)
2023-07-24 02:04:53.884 command: pack, arguments: Namespace(debug=False, destructive_mode=False)
2023-07-24 02:04:53.889 Bad rockcraft.yaml content:
- extra field 'stage-package' not permitted in 'parts.gcloud' configuration
2023-07-24 02:04:53.891 Traceback (most recent call last):
2023-07-24 02:04:53.891   File "/snap/rockcraft/959/lib/python3.8/site-packages/rockcraft/project.py", line 48[6](https://github.com/canonical/pipelines-rocks/actions/runs/5639877801/job/15275708711#step:5:7), in unmarshal
[20](https://github.com/canonical/pipelines-rocks/actions/runs/5639877801/job/15275708711#step:5:22)[23](https://github.com/canonical/pipelines-rocks/actions/runs/5639877801/job/15275708711#step:5:25)-07-[24](https://github.com/canonical/pipelines-rocks/actions/runs/5639877801/job/15275708711#step:5:26) 02:04:53.891     project = Project(**data)
2023-07-24 02:04:53.891   File "pydantic/main.py", line 331, in pydantic.main.BaseModel.__init__
2023-07-24 02:04:53.891 pydantic.error_wrappers.ValidationError: 1 validation error for Project
2023-07-24 02:04:53.891 parts -> gcloud -> stage-package
2023-07-24 02:04:53.891   extra fields not permitted (type=value_error.extra)
2023-07-24 02:04:53.891 Full execution log: '/home/runner/.local/state/rockcraft/log/rockcraft-202[30](https://github.com/canonical/pipelines-rocks/actions/runs/5639877801/job/15275708711#step:5:32)724-020453.881[37](https://github.com/canonical/pipelines-rocks/actions/runs/5639877801/job/15275708711#step:5:39)5.log'
Error: The process '/usr/bin/sg' failed with exit code 1
```

# Analysis
Syntax error is the problem. It was introduced in previous PR https://github.com/canonical/pipelines-rocks/pull/26

# Solution
Fix syntax error, i.e. use proper keyword.

**Comment by i-chvets** [comment]
@SamirPS It looks like there is syntax error. I am fixing it. Will be porviding PR shortly.

**Comment by i-chvets** [comment]
Fix is merged.
