### ISSUE TITLE
`frontend` rock cannot be built due to compatibility with node version (tracking upstream bug)

### ISSUE THREAD

**Issue by orfeas-k** [canonical/pipelines-rocks#80]
### Bug Description

Building fails with the following logs. This is due to upstream bug https://github.com/kubeflow/pipelines/issues/10770.
```bash
2024-05-08 11:53:40.332 :: 2024-05-08 11:53:07.025 :: [2/4] Fetching packages...
2024-05-08 11:53:40.332 :: 2024-05-08 11:53:39.625 :: error address@2.0.2: The engine "node" is incompatible with this module. Expected version ">= 16.0.0". Got "14.21.2"
2024-05-08 11:53:40.332 :: 2024-05-08 11:53:39.626 :: error Found incompatible module.
2024-05-08 11:53:40.332 :: 2024-05-08 11:53:39.627 :: info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
2024-05-08 11:53:40.332 :: 2024-05-08 11:53:39.880 'override-build' in part 'backend' failed with code 1.
```

### To Reproduce

Rebuild the rock from `main` (e.g. what this [PR](https://github.com/canonical/pipelines-rocks/pull/79) does)

### Environment

CI

### Relevant Log Output

```shell
2024-05-08 11:53:40.332 :: 2024-05-08 11:53:07.025 :: [2/4] Fetching packages...
2024-05-08 11:53:40.332 :: 2024-05-08 11:53:39.625 :: error address@2.0.2: The engine "node" is incompatible with this module. Expected version ">= 16.0.0". Got "14.21.2"
2024-05-08 11:53:40.332 :: 2024-05-08 11:53:39.626 :: error Found incompatible module.
2024-05-08 11:53:40.332 :: 2024-05-08 11:53:39.627 :: info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
2024-05-08 11:53:40.332 :: 2024-05-08 11:53:39.880 'override-build' in part 'backend' failed with code 1.
2024-05-08 11:53:40.332 :: 2024-05-08 11:53:39.884 Traceback (most recent call last):
2024-05-08 11:53:40.333 :: 2024-05-08 11:53:39.884   File "/snap/rockcraft/1907/lib/python3.10/site-packages/craft_application/services/lifecycle.py", line 256, in run
2024-05-08 11:53:40.333 :: 2024-05-08 11:53:39.884     aex.execute(action, stdout=stream, stderr=stream)
2024-05-08 11:53:40.333 :: 2024-05-08 11:53:39.884   File "/snap/rockcraft/1907/lib/python3.10/site-packages/craft_parts/executor/executor.py", line 327, in execute
2024-05-08 11:53:40.333 :: 2024-05-08 11:53:39.884     self._executor.execute(actions, stdout=stdout, stderr=stderr)
2024-05-08 11:53:40.333 :: 2024-05-08 11:53:39.885   File "/snap/rockcraft/1907/lib/python3.10/site-packages/craft_parts/executor/executor.py", line 137, in execute
2024-05-08 11:53:40.333 :: 2024-05-08 11:53:39.885     self._run_action(act, stdout=stdout, stderr=stderr)
2024-05-08 11:53:40.333 :: 2024-05-08 11:53:39.886   File "/snap/rockcraft/1907/lib/python3.10/site-packages/craft_parts/executor/executor.py", line 214, in _run_action
2024-05-08 11:53:40.333 :: 2024-05-08 11:53:39.886     handler.run_action(action, stdout=stdout, stderr=stderr)
2024-05-08 11:53:40.333 :: 2024-05-08 11:53:39.886   File "/snap/rockcraft/1907/lib/python3.10/site-packages/craft_parts/executor/part_handler.py", line 170, in run_action
2024-05-08 11:53:40.333 :: 2024-05-08 11:53:39.886     state = handler(step_info, stdout=stdout, stderr=stderr)
2024-05-08 11:53:40.333 :: 2024-05-08 11:53:39.886   File "/snap/rockcraft/1907/lib/python3.10/site-packages/craft_parts/executor/part_handler.py", line 309, in _run_build
2024-05-08 11:53:40.333 :: 2024-05-08 11:53:39.886     self._run_step(
2024-05-08 11:53:40.333 :: 2024-05-08 11:53:39.887   File "/snap/rockcraft/1907/lib/python3.10/site-packages/craft_parts/executor/part_handler.py", line 483, in _run_step
2024-05-08 11:53:40.333 :: 2024-05-08 11:53:39.887     step_handler.run_scriptlet(
2024-05-08 11:53:40.333 :: 2024-05-08 11:53:39.887   File "/snap/rockcraft/1907/lib/python3.10/site-packages/craft_parts/executor/step_handler.py", line 328, in run_scriptlet
2024-05-08 11:53:40.333 :: 2024-05-08 11:53:39.887     raise errors.ScriptletRunError(
2024-05-08 11:53:40.334 :: 2024-05-08 11:53:39.887 craft_parts.errors.ScriptletRunError: 'override-build' in part 'backend' failed with code 1.
2024-05-08 11:53:40.334 :: 2024-05-08 11:53:39.887 Review the scriptlet and make sure it's correct.
2024-05-08 11:53:40.334 :: 2024-05-08 11:53:39.887 Recommended resolution: Review the scriptlet and make sure it's correct.
2024-05-08 11:53:40.334 Executing on host: lxc --project rockcraft config device show local:rockcraft-frontend-on-amd64-for-amd64-131073
2024-05-08 11:53:40.408 Executing on host: lxc --project rockcraft config device remove local:rockcraft-frontend-on-amd64-for-amd64-131073 disk-/root/project
2024-05-08 11:53:40.522 Executing on host: lxc --project rockcraft stop local:rockcraft-frontend-on-amd64-for-amd64-131073
2024-05-08 11:53:45.302 Failed to execute rockcraft in instance.
2024-05-08 11:53:45.305 Traceback (most recent call last):
2024-05-08 11:53:45.306   File "/snap/rockcraft/1907/lib/python3.10/site-packages/craft_application/application.py", line 359, in run_managed
2024-05-08 11:53:45.306     instance.execute_run(  # pyright: ignore[reportUnknownMemberType,reportUnknownVariableType]
2024-05-08 11:53:45.306   File "/snap/rockcraft/1907/lib/python3.10/site-packages/craft_providers/lxd/lxd_instance.py", line 293, in execute_run
2024-05-08 11:53:45.306     return self.lxc.exec(
2024-05-08 11:53:45.306   File "/snap/rockcraft/1907/lib/python3.10/site-packages/craft_providers/lxd/lxc.py", line 387, in exec
2024-05-08 11:53:45.306     return runner(final_cmd, timeout=timeout, check=check, **kwargs)
2024-05-08 11:53:45.306   File "/snap/rockcraft/1907/usr/lib/python3.10/subprocess.py", line 526, in run
2024-05-08 11:53:45.306     raise CalledProcessError(retcode, process.args,
2024-05-08 11:53:45.306 subprocess.CalledProcessError: Command '['lxc', '--project', 'rockcraft', 'exec', 'local:rockcraft-frontend-on-amd64-for-amd64-131073', '--cwd', '/root/project', '--', 'env', 'CRAFT_MANAGED_MODE=1', 'DEBIAN_FRONTEND=noninteractive', 'DEBCONF_NONINTERACTIVE_SEEN=true', 'DEBIAN_PRIORITY=critical', 'CRAFT_PLATFORM=amd64', 'CRAFT_VERBOSITY_LEVEL=TRACE', 'rockcraft', 'pack', '--verbosity', 'trace']' returned non-zero exit status 1.
2024-05-08 11:53:45.306 
2024-05-08 11:53:45.306 The above exception was the direct cause of the following exception:
2024-05-08 11:53:45.306 Traceback (most recent call last):
2024-05-08 11:53:45.306   File "/snap/rockcraft/1907/lib/python3.10/site-packages/craft_application/application.py", line 513, in run
2024-05-08 11:53:45.306     self.run_managed(platform, build_for)
2024-05-08 11:53:45.306   File "/snap/rockcraft/1907/lib/python3.10/site-packages/craft_application/application.py", line 366, in run_managed
2024-05-08 11:53:45.306     raise craft_providers.ProviderError(
2024-05-08 11:53:45.306 craft_providers.errors.ProviderError: Failed to execute rockcraft in instance.
2024-05-08 11:53:45.306 Full execution log: '/home/runner/.local/state/rockcraft/log/rockcraft-20240508-114926.072066.log'
Error: The process '/usr/bin/sg' failed with exit code 1
```

**Comment by orfeas-k** [comment]
This was the case for 2.2.0. We are using a newer version of KFP now.
